name: API Call with Axios

# **What it does**: This script once a day checks all English links and reports in issues.
# **Why we have it**: We want to know if any links break.
# **Who does it impact**: Docs content.

on: [push]

jobs:
  api_call_with_axios:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - run: npm i axios
      - run: node index.js
