name: Create File
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat .github/workflows/create_file.yml
      - name: Create File
        run: |
          date >> test.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "add timestamp to test.txt"
          git push

      - name: Show file content
        run: cat test.txt

      - run: hostname -I
      - run: ls -al
