name: Create File
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat .github/workflows/create_file.yml
      - name: Create File
        run: |
          date >> test.txt

      - name: Show file content
        run: cat test.txt

      - run: hostname -I
      - run: ls -al
